name: onlinejournal
description: Online journal for marks in school

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  # UI
  cupertino_icons: ^0.1.3
  # state management
  flutter_bloc: ^3.2.0
  # dart support
  dartz: ^0.8.9
  equatable: ^1.1.0
  # service locator
  get_it: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1


flutter:

  uses-material-design: true
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700